[package]
name = "rupy"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
pollster = "0.3.0"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }
wgpu = "22.1.0"  
winit = { version = "0.30.5", features = ["rwh_06"] }

log = { version = "0.4.22", optional = true }
env_logger = { version = "0.11.5", optional = true }

[features]
default = ["logging"]
logging = ["env_logger", "log"]



[lib]
path = "src/lib.rs"

[[bin]]
name = "rupy"
path = "src/main.rs"
